/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class Library {
    public static void main(String[] args) {
    	int[] in1 = {-4,-1,0,3,10};
    	int[] in2 = {-7,-3,2,3,11};
    	int[] result;
    	result = sortedSquares(in1);
    	for (int i : result) {
			System.out.print(i+" ");
		}
    	System.out.println();
    	result = sortedSquares(in2);
    	for (int i : result) {
			System.out.print(i + " ");
		}
    }
    public static int[] sortedSquares(int[] A) {
       //List<Integer> result = new ArrayList<Integer>(A.length); 
       int[] result = new int[A.length];
    	int i = 0;
       while(i < A.length) {
    	   result[i] = A[i] * A[i];
    	   i++;
       }
       Arrays.sort(result);
       return result;
    }
}
