/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class Library {
    public static void main(String[] args) {
    	String[] emails = {
    			new String("test.email+alex@leetcode.com"),
    			new String("test.e.mail+bob.cathy@leetcode.com"),
    			new String("testemail+david@lee.tcode.com")
    	};
    	String[] emails2 = {"abc@def.com","abcd@ef.com","ab.c@def.com"};
    	String[] emails3 = {"a@leetcode.com","b@leetcode.com","c@leetcode.com"};
    	System.out.println(numUniqueEmails(emails3));
    	System.out.println(numUniqueEmails(emails));
    	System.out.println(numUniqueEmails(emails2));
	}
    public static int numUniqueEmails(String[] emails) {
	    	//split
	    	StringBuffer localName = new StringBuffer();
	    	StringBuffer domainName = new StringBuffer();
	    	StringBuffer emailName = new StringBuffer();
	    	Set<String> resultSet = new HashSet<String>();
	    	char[] chTemp;
	    	for(int i = 0;i < emails.length;i++) {
	    		chTemp = emails[i].toCharArray();
	    		for(int j = 0;j < chTemp.length;j++) {
	    			if(chTemp[j] == '@') {
	    				localName.append(emails[i].substring(0, j));
		    			domainName.append(emails[i].substring(j+1, chTemp.length));
		    			for(int k = 0;k < localName.length();k++) {
		    				if(localName.charAt(k) == '.' || localName.charAt(k) == '@') {
		    					localName.deleteCharAt(k);
		    				}
		    				else if(localName.charAt(k) == '+') {
		    					localName.delete(k, localName.length());
		    				}
		    			}
	    				emailName.append(localName).append("@").append(domainName);
	    				resultSet.add(emailName.toString());
	    				localName.setLength(0);
	    				domainName.setLength(0);
	    				emailName.setLength(0);	
	    			}
	    		}
	    	}
	    	return resultSet.size();
    }
}
