/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class Library {
    public static void main(String[] args) {
    	int[] as = {3,1,2,4};
    	int[] result = sortArrayByParity(as);
    	for (int i : result) {
			System.out.println(i);
		}
    }
    public static int[] sortArrayByParity(int[] A) {
    	int[] result = new int[A.length];
    	int current = 0;
    	for(int i = 0;i < A.length;i++) {
    		if(A[i] % 2 == 0)
    			result[current++] = A[i];
    	}
    	for(int i = 0;i < A.length;i++) {
    		if(A[i] % 2 != 0)
    			result[current++] = A[i];
    	}
    	return result;
    }
}
