/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Library {
    public static void main(String[] args) {
    	String ts = "Hello";
    	String ts2 = "LOVELY";
    	System.out.println(toLowerCase(ts));
    	System.out.println(toLowerCase(ts2));
	}
    //a=A+32;
    public static String toLowerCase(String str) {
        StringBuffer result = new StringBuffer();
        int i = 0;
        char[] tmp = str.toCharArray();
        for(i = 0;i < str.length();i++) {
        	if(tmp[i] >= 'A' && tmp[i] <= 'Z') {
        		tmp[i] = (char) (tmp[i] + 32);
        		result.append(tmp[i]);
        	}else {
        		result.append(tmp[i]);
			}
        }
        return result.toString();
    }
}
